### PR TITLE
Welcome, KS & FL 🍍

### LINKED ISSUE #9: Missing data due to differences in reporting `dv`
We set up this pipeline to pull down daily value data for all active gages. Unfortunately, we learned that our assumption that the "mean" stat code (`00003`) would be used if there was any `dv` data was wrong. The stat code used to report daily groundwater varies widely by state (see map below). Thus, in the current setup where we use `stat_cd = "00003"`, we are missing huge swaths of GW sites and entire states. 

We will likely need to switch over to generating a daily value from instantaneous data. Could save some processing time by only doing this for sites without the `dv` data already. That is similar to how `national-flow-observations` is setup. This change will also need to happen for how the historic data was generated. 

image

Code used to generate this map (need to run in pipeline):

```r
# Why does it seem like we are missing so many sites across the country?
# E.g. there are none in OH but OH has real-time sites on GWW
# https://groundwaterwatch.usgs.gov/StateMap.asp?sa=OH&sc=39

# This OH site has real time daily data for 72019 but only stat code 00001 (max)
# It also has `uv` for 72019. I suppose we could do all of our data pulls for
#   `uv` and then make our own summary ...
x <- whatNWISdata(siteNumber = "383638082103300")

# What other sites are we missing that have `00001` instead?

source("1_fetch/src/fetch_nwis.R")

fetch_gw_sites("sites_max.rds", "2020-10-01", "2020-12-31", 
               c(-124.409591, 24.523096, -66.949895, 49.384358), 
               param_cd = '72019', stat_cd = '00001')
fetch_gw_site_info("sites_max_info.csv", "sites_max.rds")

# Do the same but for `00002`

fetch_gw_sites("sites_min.rds", "2020-10-01", "2020-12-31", 
               c(-124.409591, 24.523096, -66.949895, 49.384358), 
               param_cd = '72019', stat_cd = '00002')
fetch_gw_site_info("sites_min_info.csv", "sites_min.rds")

# Also, which have `uv`??
fetch_gw_sites("sites_uv.rds", "2020-10-01", "2020-12-31", 
               c(-124.409591, 24.523096, -66.949895, 49.384358), 
               param_cd = '72019', service = 'uv')
fetch_gw_site_info("sites_uv_info.csv", "sites_uv.rds")

proj_str <- scmake("proj_str")
convert_to_sf <- function(data, proj) {
  data %>% 
    st_as_sf(coords = c("dec_long_va", "dec_lat_va"), crs = "+proj=longlat +datum=WGS84") %>% 
    st_transform(proj_str)
}

# Now map & compare
fy20q1_mean_sites <- read_csv("1_fetch/out/gw_site_info.csv", col_types = "cccnn") %>% convert_to_sf(proj_str)
fy20q1_min_sites <- read_csv("sites_min_info.csv", col_types = "cccnn") %>% convert_to_sf(proj_str)
fy20q1_max_sites <- read_csv("sites_max_info.csv", col_types = "cccnn") %>% convert_to_sf(proj_str)
fy20q1_uv_sites <- read_csv("sites_uv_info.csv", col_types = "cccnn") %>% convert_to_sf(proj_str)

usa_sf <- st_as_sf(maps::map('state', fill=TRUE, plot=FALSE)) %>% st_transform(proj_str)

cols_to_use <- viridis::viridis(4)

par(mar = c(0,0,0,0))
plot(st_geometry(usa_sf), col = "#fcf8e8", border = "lightgrey", bg = "grey")
plot(st_geometry(fy20q1_uv_sites), col = cols_to_use[4], cex = 0.8, pch = 20, add=TRUE)
plot(st_geometry(fy20q1_min_sites), col = cols_to_use[2], cex = 0.8, pch = 20, add=TRUE)
plot(st_geometry(fy20q1_max_sites), col = cols_to_use[3], cex = 0.8, pch = 20, add=TRUE)
plot(st_geometry(fy20q1_mean_sites), col = cols_to_use[1], cex = 0.8, pch = 20, add=TRUE)
legend("bottomleft", pch = 20, cex = 0.8, col = cols_to_use[c(4, 3, 2, 1)], bty = "n",
       legend = c("UV only", "DV 00002 (min)", "DV 00001 (max)", "DV 00003 (mean)"),
       title = "Service queried (listed in\norder added to map)")
title(main = "Available FY20 Q1 GWL Data\nby Service & Stat Code Type", 
      line = -3.5, cex.main = 1.5)
```

### PR DESCRIPTION
**Pull request by lindsayplatt**
Got KS & FL full integrated into the pipeline now! Historic data & in the main pipeline. Yay! You should be able to just run `scmake()` and create the image below (should take a few hours, not a few days!) Fixes #9 

image

I don't know what is going on with the sites who are in the top left, will dig into that later but it looks cool :)

### CODE REVIEW

**Review by collnell — APPROVED** [review]
Amazing work on this!

**Comment by collnell** [comment]
When I run `scmake()` I get this error
```Restoring previous version of 1_fetch/out/historic_gw_site_info_filtered.rds
 Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Moved Permanently (HTTP 301). ```

**Review by collnell — COMMENTED** [review]
Something goes awry around `2_process/out/gw_daily_quantiles.csv:`
The historic and current data appear as expected, but produces NAs when the quantiles are calculated. There's a huge number of warning messages that `Quantiles not available for...returning NA` for what seems like all sites. 

When digging into the `compare_to_historic` function, there's about 1000 more sites in `inverse_sites` than `gw_sites`, is this related? Or is this just because there were sites dropped because they are not currently active? It also seems like there are fewer non-inverse sites than I would expect, the following gives me 283

```read_csv("1_fetch/out/gw_data.csv", col_types = 'cDn') %>% 
  filter(!(site_no %in% inverse_sites)) %>% 
  pull(site_no) %>%
  unique %>% length```

File: 2_process/src/compare_to_historic.R [hunk 1]
```diff
@@ -1,5 +1,5 @@
 
-compare_to_historic <- function(target_name, historic_quantile_fn, current_data_fn) {
+compare_to_historic <- function(target_name, historic_quantile_fn, current_data_fn, inverse_sites) {
   
   current_data <- read_csv(current_data_fn, col_types = 'cDn')
```
Comment (collnell) [inline 2_process/src/compare_to_historic.R:4]: should this be `col_types = 'cDn'`?

File: 2_process/src/compare_to_historic.R [hunk 2]
```diff
@@ -21,19 +25,23 @@ compare_to_historic <- function(target_name, historic_quantile_fn, current_data_
...
+      # Add flag for whether an inverse of the GWL value should be used
+      mutate(is_inverse = site_no %in% inverse_sites) %>% 
       # Figure out the corresponding quantile for each daily value
       # If there are no non-NA quantiles available, return NA
       rowwise() %>% 
       mutate(daily_quant = ifelse(
         nrow(site_quantiles) > 0, 
-        yes = approx(x = site_quantiles$quantile_va, y = site_quantiles$quantile_nm, xout = GWL)$y,
+        yes = approx(x = site_quantiles$quantile_va, y = site_quantiles$quantile_nm, 
+                     xout = GWL*ifelse(is_inverse, -1, 1))$y,
```
Comment (collnell) [inline 2_process/src/compare_to_historic.R:36]: I think the ifelse logic to invert the values also needs to be done to `x = site_quantiles$quantile_va` so that the interpolation is applied to values of the same sign +/-

Comment (collnell) [reply 2_process/src/compare_to_historic.R:36]: With this change I am still missing a number of sites 
image

Comment (lindsayplatt) [reply 2_process/src/compare_to_historic.R:36]: It seems like you don't have the new historic data, which might be why there are so many `Quantiles not available for...returning NA` messages. I wonder if you can try:

```r
library(scipiper)
scmake("1_fetch/out/historic_gw_site_info_filtered.rds", force=TRUE)
scmake("1_fetch/out/historic_gw_quantiles.csv", force=TRUE)
```

If you get an AWS error, try 1) getting on VPN, and 2) updating `dssecrets` (pull from upstream then build the pkg) because the AWS key was recently updated by David.

Comment (lindsayplatt) [reply 2_process/src/compare_to_historic.R:36]: The quantiles are already reversed when they are originally generated (see [here](https://github.com/USGS-VIZLAB/gw-conditions/pull/24/files#diff-1c2392b3deb15657a887700756f213e59af7ba47bb0dbb7f659db96e00885d8eR17)), so I should just be inversing the groundwater levels being compared to them (_right?_)

File: 2_process/src/compare_to_historic.R (hunk 1 above)
Comment (lindsayplatt) [reply 2_process/src/compare_to_historic.R:4]: I don't think so ... I am pretty sure that the data has `site_no`, `Date`, and then `GWL` as the columns.

Comment (collnell) [reply 2_process/src/compare_to_historic.R:4]: sorry made a mistake, this comment was meant for `historic_quantiles` that has `site_no`, `quantile_nm`, `quantile_va`.

File: 2_process/src/compare_to_historic.R (hunk 2 above)
Comment (collnell) [reply 2_process/src/compare_to_historic.R:36]: yes. This resolved the issue

Comment (collnell) [reply 2_process/src/compare_to_historic.R:36]: image

File: 2_process/src/compare_to_historic.R (hunk 1 above)
Comment (lindsayplatt) [reply 2_process/src/compare_to_historic.R:4]: ahhhh I see now. I did have that as `cnn` at one time, but changed to `ccn` because the `nm` in `quantile_nm` was intended to be read as "name" of the quantile (not "number") and it felt silly to have something called "name" but be numeric. I can see now that my decision likely has downstream consequences when `quantile_nm` is used in `approx`. I will change!

**Comment by collnell** [comment]
The resulting svg output has several `<g>` elements with `transform="translate(NA NA)`. I suspect these are the same sites  in the upper left corner of the output. These seem to be crashing vue when the output svg is used as a standalone component

**Comment by lindsayplatt** [comment]
Merging, but noted that `translate(NA NA)` problem in #25
